# Generated by Django 4.2.1 on 2023-05-23 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=40, verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Place Name')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='userapp.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of tour')),
                ('description', models.TextField(max_length=50, verbose_name='Description')),
                ('duration', models.IntegerField(verbose_name='Duration')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='userapp.destination')),
            ],
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
