# Generated by Django 4.2.1 on 2023-05-23 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_destination_places_tours_delete_usermodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destination',
            new_name='Destinations',
        ),
        migrations.AlterModelOptions(
            name='destinations',
            options={'verbose_name': 'Destination', 'verbose_name_plural': 'Destinations'},
        ),
        migrations.AlterModelOptions(
            name='places',
            options={'verbose_name': 'Place', 'verbose_name_plural': 'Places'},
        ),
        migrations.AlterModelOptions(
            name='tours',
            options={'verbose_name': 'Tour', 'verbose_name_plural': 'Tours'},
        ),
    ]
