# Generated by Django 4.2.1 on 2023-06-01 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
